Add more storybook CI steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,47 +74,48 @@ jobs:
         echo ::set-output name=version_minor::${MINOR}
         echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
         echo ::set-output name=push::${PUSH}
-  #   - name: Use Node.js ${{ env.node_version }}
-  #     uses: actions/setup-node@v2.1.5
-  #     with:
-  #       node-version: ${{ env.node_version }}
-  #   - name: Build storybook
-  #     run: npm run build:storybook
-  #   - name: Commit storybook
-  #     run: |
-  #       git clone ${{ env.clone_url }} \
-  #         --branch gh-pages --single-branch gh-pages
-  #       # Update gh-pages: version specified
-  #       TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
-  #       mkdir -p ${TARGET_DIR}
-  #       cp -R storybook-static/* ${TARGET_DIR}
-  #       # Update gh-pages: latest, major, and minor versions
-  #       if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
-  #         # Update major version (e.g. "1.2.3" => "1")
-  #         TARGET_DIR=gh-pages/latest
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #         # Update major version (e.g. "1.2.3" => "1")
-  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #         # Update minor version (e.g. "1.2.3" => "1.2")
-  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #       fi
-  #       cd gh-pages
-  #       git config --local user.email "action@github.com"
-  #       git config --local user.name "GitHub Action"
-  #       git add .
-  #       git commit -m "Update storybook" -a || true
-  #       # The above command will fail if no changes were present, so we ignore
-  #       # that.
-  #   - name: Push changes
-  #     if: steps.prep.outputs.push == 'true'
-  #     uses: ad-m/github-push-action@master
-  #     with:
-  #       branch: gh-pages
-  #       directory: gh-pages
-  #       github_token: ${{ secrets.GITHUB_TOKEN }}
-  #       force: true
+    - name: Use Node.js ${{ env.node_version }}
+      uses: actions/setup-node@v2.1.5
+      with:
+        node-version: ${{ env.node_version }}
+    - run: npm ci
+    - name: Build storybook
+      run: npm run build:storybook
+    - name: Commit storybook
+      run: |
+        git clone ${{ env.clone_url }} \
+          --branch gh-pages --single-branch gh-pages
+        # Update gh-pages: version specified
+        TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
+        mkdir -p ${TARGET_DIR}
+        cp -R storybook-static/* ${TARGET_DIR}
+        # Update gh-pages: latest, major, and minor versions
+        if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
+          # Update major version (e.g. "1.2.3" => "1")
+          TARGET_DIR=gh-pages/latest
+          mkdir -p ${TARGET_DIR}
+          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+          # Update major version (e.g. "1.2.3" => "1")
+          TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}
+          mkdir -p ${TARGET_DIR}
+          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+          # Update minor version (e.g. "1.2.3" => "1.2")
+          TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}
+          mkdir -p ${TARGET_DIR}
+          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+        fi
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update storybook" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      if: steps.prep.outputs.push == 'true'
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        force: true
