Tmp disable storybook job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,86 +35,86 @@ jobs:
     # - name: Run e2e tests
     #   run: npm run e2e
 
-  build-and-publish-storybook:
-    needs: [test]
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-    - name: Prepare
-      id: prep
-      run: |
-        VERSION=noop
-        PUSH=false
-        if [ "${{ github.event_name }}" = "schedule" ]; then
-          VERSION=nightly
-          PUSH=true
-        elif [[ $GITHUB_REF == refs/tags/* ]]; then
-          VERSION=${GITHUB_REF#refs/tags/}
-        elif [[ $GITHUB_REF == refs/heads/* ]]; then
-          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
-          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
-            VERSION=edge
-            PUSH=true
-          elif [ "develop" = "$VERSION" ]; then
-            # If the branch develop is the default branch, the doc will be pushed
-            # to the folder edge but not the folder develop..
-            PUSH=true
-          fi
-        elif [[ $GITHUB_REF == refs/pull/* ]]; then
-          VERSION=pr-${{ github.event.number }}
-          PUSH=false
-        fi
-        if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-          MINOR=${VERSION%.*}
-          MAJOR=${MINOR%.*}
-          PUSH=true
-        fi
-        echo ::set-output name=version::${VERSION}
-        echo ::set-output name=version_major::${MAJOR}
-        echo ::set-output name=version_minor::${MINOR}
-        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
-        echo ::set-output name=push::${PUSH}
-    - name: Use Node.js ${{ env.node_version }}
-      uses: actions/setup-node@v2.1.5
-      with:
-        node-version: ${{ env.node_version }}
-    - name: Build storybook
-      run: npm run build:storybook
-    - name: Commit storybook
-      run: |
-        git clone ${{ env.clone_url }} \
-          --branch gh-pages --single-branch gh-pages
-        # Update gh-pages: version specified
-        TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
-        mkdir -p ${TARGET_DIR}
-        cp -R storybook-static/* ${TARGET_DIR}
-        # Update gh-pages: latest, major, and minor versions
-        if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
-          # Update major version (e.g. "1.2.3" => "1")
-          TARGET_DIR=gh-pages/latest
-          mkdir -p ${TARGET_DIR}
-          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-          # Update major version (e.g. "1.2.3" => "1")
-          TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}
-          mkdir -p ${TARGET_DIR}
-          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-          # Update minor version (e.g. "1.2.3" => "1.2")
-          TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}
-          mkdir -p ${TARGET_DIR}
-          cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-        fi
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update storybook" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      if: steps.prep.outputs.push == 'true'
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        force: true
+  # build-and-publish-storybook:
+  #   needs: [test]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Prepare
+  #     id: prep
+  #     run: |
+  #       VERSION=noop
+  #       PUSH=false
+  #       if [ "${{ github.event_name }}" = "schedule" ]; then
+  #         VERSION=nightly
+  #         PUSH=true
+  #       elif [[ $GITHUB_REF == refs/tags/* ]]; then
+  #         VERSION=${GITHUB_REF#refs/tags/}
+  #       elif [[ $GITHUB_REF == refs/heads/* ]]; then
+  #         VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
+  #         if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
+  #           VERSION=edge
+  #           PUSH=true
+  #         elif [ "develop" = "$VERSION" ]; then
+  #           # If the branch develop is the default branch, the doc will be pushed
+  #           # to the folder edge but not the folder develop..
+  #           PUSH=true
+  #         fi
+  #       elif [[ $GITHUB_REF == refs/pull/* ]]; then
+  #         VERSION=pr-${{ github.event.number }}
+  #         PUSH=false
+  #       fi
+  #       if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+  #         MINOR=${VERSION%.*}
+  #         MAJOR=${MINOR%.*}
+  #         PUSH=true
+  #       fi
+  #       echo ::set-output name=version::${VERSION}
+  #       echo ::set-output name=version_major::${MAJOR}
+  #       echo ::set-output name=version_minor::${MINOR}
+  #       echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+  #       echo ::set-output name=push::${PUSH}
+  #   - name: Use Node.js ${{ env.node_version }}
+  #     uses: actions/setup-node@v2.1.5
+  #     with:
+  #       node-version: ${{ env.node_version }}
+  #   - name: Build storybook
+  #     run: npm run build:storybook
+  #   - name: Commit storybook
+  #     run: |
+  #       git clone ${{ env.clone_url }} \
+  #         --branch gh-pages --single-branch gh-pages
+  #       # Update gh-pages: version specified
+  #       TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
+  #       mkdir -p ${TARGET_DIR}
+  #       cp -R storybook-static/* ${TARGET_DIR}
+  #       # Update gh-pages: latest, major, and minor versions
+  #       if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
+  #         # Update major version (e.g. "1.2.3" => "1")
+  #         TARGET_DIR=gh-pages/latest
+  #         mkdir -p ${TARGET_DIR}
+  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+  #         # Update major version (e.g. "1.2.3" => "1")
+  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}
+  #         mkdir -p ${TARGET_DIR}
+  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+  #         # Update minor version (e.g. "1.2.3" => "1.2")
+  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}
+  #         mkdir -p ${TARGET_DIR}
+  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
+  #       fi
+  #       cd gh-pages
+  #       git config --local user.email "action@github.com"
+  #       git config --local user.name "GitHub Action"
+  #       git add .
+  #       git commit -m "Update storybook" -a || true
+  #       # The above command will fail if no changes were present, so we ignore
+  #       # that.
+  #   - name: Push changes
+  #     if: steps.prep.outputs.push == 'true'
+  #     uses: ad-m/github-push-action@master
+  #     with:
+  #       branch: gh-pages
+  #       directory: gh-pages
+  #       github_token: ${{ secrets.GITHUB_TOKEN }}
+  #       force: true
